# bash/zsh git prompt support
#
# Copyright (C) 2006,2007 Shawn O. Pearce <spearce@spearce.org>
# Distributed under the GNU General Public License, version 2.0.
#
# This script allows you to see repository status in your prompt.
#
# To enable:
#
#    1) Copy this file to somewhere (e.g. ~/.git-prompt.sh).
#    2) Add the following line to your .bashrc/.zshrc/.profile:
#        . ~/.git-prompt.sh   # dot path/to/this-file
#    3a) Change your PS1 to call __git_ps1 as
#        command-substitution:
#        Bash: PS1='[\u@\h \W$(__git_ps1 " (%s)")]\$ '
#        ZSH:  setopt PROMPT_SUBST ; PS1='[%n@%m %c$(__git_ps1 " (%s)")]\$ '
#        the optional argument will be used as format string.
#    3b) Alternatively, for a slightly faster prompt, __git_ps1 can
#        be used for PROMPT_COMMAND in Bash or for precmd() in Zsh
#        with two parameters, <pre> and <post>, which are strings
#        you would put in $PS1 before and after the status string
#        generated by the git-prompt machinery.  e.g.
#        Bash: PROMPT_COMMAND='__git_ps1 "\u@\h:\w" "\\\$ "'
#          will show username, at-sign, host, colon, cwd, then
#          various status string, followed by dollar and SP, as
#          your prompt.
#        ZSH:  precmd () { __git_ps1 "%n" ":%~$ " "|%s" }
#          will show username, pipe, then various status string,
#          followed by colon, cwd, dollar and SP, as your prompt.
#        Optionally, you can supply a third argument with a printf
#        format string to finetune the output of the branch status
#
#    See notes below about compatibility with other shells.
#
# The repository status will be displayed only if you are currently in a
# git repository. The %s token is the placeholder for the shown status.
#
# The prompt status always includes the current branch name.
#
# In addition, if you set GIT_PS1_SHOWDIRTYSTATE to a nonempty value,
# unstaged (*) and staged (+) changes will be shown next to the branch
# name.  You can configure this per-repository with the
# bash.showDirtyState variable, which defaults to true once
# GIT_PS1_SHOWDIRTYSTATE is enabled.
#
# You can also see if currently something is stashed, by setting
# GIT_PS1_SHOWSTASHSTATE to a nonempty value. If something is stashed,
# then a '$' will be shown next to the branch name.
#
# If you would like to see if there're untracked files, then you can set
# GIT_PS1_SHOWUNTRACKEDFILES to a nonempty value. If there're untracked
# files, then a '%' will be shown next to the branch name.  You can
# configure this per-repository with the bash.showUntrackedFiles
# variable, which defaults to true once GIT_PS1_SHOWUNTRACKEDFILES is
# enabled.
#
# If you would like to see the difference between HEAD and its upstream,
# set GIT_PS1_SHOWUPSTREAM="auto".  A "<" indicates you are behind, ">"
# indicates you are ahead, "<>" indicates you have diverged and "="
# indicates that there is no difference. You can further control
# behaviour by setting GIT_PS1_SHOWUPSTREAM to a space-separated list
# of values:
#
#     verbose       show number of commits ahead/behind (+/-) upstream
#     name          if verbose, then also show the upstream abbrev name
#     legacy        don't use the '--count' option available in recent
#                   versions of git-rev-list
#     git           always compare HEAD to @{upstream}
#     svn           always compare HEAD to your SVN upstream
#
# By default, __git_ps1 will compare HEAD to your SVN upstream if it can
# find one, or @{upstream} otherwise.  Once you have set
# GIT_PS1_SHOWUPSTREAM, you can override it on a per-repository basis by
# setting the bash.showUpstream config variable.
#
# You can change the separator between the branch name and the above
# state symbols by setting GIT_PS1_STATESEPARATOR. The default separator
# is SP.
#
# When there is an in-progress operation such as a merge, rebase,
# revert, cherry-pick, or bisect, the prompt will include information
# related to the operation, often in the form "|<OPERATION-NAME>".
#
# When the repository has a sparse-checkout, a notification of the form
# "|SPARSE" will be included in the prompt.  This can be shortened to a
# single '?' character by setting GIT_PS1_COMPRESSSPARSESTATE, or omitted
# by setting GIT_PS1_OMITSPARSESTATE.
#
# If you would like to see a notification on the prompt when there are
# unresolved conflicts, set GIT_PS1_SHOWCONFLICTSTATE to "yes". The
# prompt will include "|CONFLICT".
#
# If you would like to see more information about the identity of
# commits checked out as a detached HEAD, set GIT_PS1_DESCRIBE_STYLE
# to one of these values:
#
#     contains      relative to newer annotated tag (v1.6.3.2~35)
#     branch        relative to newer tag or branch (master~4)
#     describe      relative to older annotated tag (v1.6.3.1-13-gdd42c2f)
#     tag           relative to any older tag (v1.6.3.1-13-gdd42c2f)
#     default       exactly matching tag
#
# If you would like a colored hint about the current dirty state, set
# GIT_PS1_SHOWCOLORHINTS to a nonempty value. The colors are based on
# the colored output of "git status -sb".
#
# If you would like __git_ps1 to do nothing in the case when the current
# directory is set up to be ignored by git, then set
# GIT_PS1_HIDE_IF_PWD_IGNORED to a nonempty value. Override this on the
# repository level by setting bash.hideIfPwdIgnored to "false".
#
# Compatibility with other shells (beyond bash/zsh):
#
#    We require posix-ish shell plus "local" support, which is most
#    shells (even pdksh), but excluding ksh93 (because no "local").
#
#    Prompt integration might differ between shells, but the gist is
#    to load it once on shell init with '. path/to/git-prompt.sh',
#    set GIT_PS1* vars once as needed, and either place $(__git_ps1..)
#    inside PS1 once (0/1 args), or, before each prompt is displayed,
#    call __git_ps1 (2/3 args) which sets PS1 with the status embedded.
#
#    Many shells support the 1st method of command substitution,
#    though some might need to first enable cmd substitution in PS1.
#
#    When using colors, each escape sequence is wrapped between byte
#    values 1 and 2 (control chars SOH, STX, respectively), which are
#    invisible at the output, but for bash/readline they mark 0-width
#    strings (SGR color sequences) when calculating the on-screen
#    prompt width, to maintain correct input editing at the prompt.
#
#    To replace or disable the 0-width markers, set GIT_PS1_COLOR_PRE
#    and GIT_PS1_COLOR_POST to other markers, or empty (nul) to not
#    use markers. For instance, some shells support '\[' and '\]' as
#    start/end markers in PS1 - when invoking __git_ps1 with 3/4 args,
#    but it may or may not work in command substitution mode. YMMV.
#
#    If the shell doesn't support 0-width markers and editing behaves
#    incorrectly when using colors in __git_ps1, then, other than
#    disabling color, it might be solved using multi-line prompt,
#    where the git status is not at the last line, e.g.:
#      PS1='\n\w \u@\h$(__git_ps1 " (%s)")\n\$ '

# check whether printf supports -v
__git_printf_supports_v=
printf -v __git_printf_supports_v -- '%s' yes >/dev/null 2>&1

# like __git_SOH=$'\001' etc but works also in shells without $'...'
eval "$(printf '
	__git_SOH="\001" __git_STX="\002" __git_ESC="\033"
	__git_LF="\n" __git_CRLF="\r\n"
')"

# stores the divergence from upstream in $p
# used by GIT_PS1_SHOWUPSTREAM
__git_ps1_show_upstream ()
{
	local key value
	local svn_remotes="" svn_url_pattern="" count n
	local upstream_type=git legacy="" verbose="" name=""
	local LF="$__git_LF"

	# get some config options from git-config
	local output="$(git config -z --get-regexp '^(svn-remote\..*\.url|bash\.showupstream)$' 2>/dev/null | tr '\0\n' '\n ')"
	while read -r key value; do
		case "$key" in
		bash.showupstream)
			GIT_PS1_SHOWUPSTREAM="$value"
			if [ -z "${GIT_PS1_SHOWUPSTREAM}" ]; then
				p=""
				return
			fi
			;;
		svn-remote.*.url)
			svn_remotes=${svn_remotes}${value}${LF}  # URI\nURI\n...
			svn_url_pattern="$svn_url_pattern\\|$value"
			upstream_type=svn+git # default upstream type is SVN if available, else git
			;;
		esac
	done <<-OUTPUT
		$output
	OUTPUT

	# parse configuration values
	local option
	for option in ${GIT_PS1_SHOWUPSTREAM-}; do
		case "$option" in
		git|svn) upstream_type="$option" ;;
		verbose) verbose=1 ;;
		legacy)  legacy=1  ;;
		name)    name=1 ;;
		esac
	done

	# Find our upstream type
	case "$upstream_type" in
	git)    upstream_type="@{upstream}" ;;
	svn*)
		# successful svn-upstream resolution:
		# - get the list of configured svn-remotes ($svn_remotes set above)
		# - get the last commit which seems from one of our svn-remotes
		# - confirm that it is from one of the svn-remotes
		# - use $GIT_SVN_ID if set, else "git-svn"

		# get upstream from "git-svn-id: UPSTRM@N HASH" in a commit message
		# (git-svn uses essentially the same procedure internally)
		local svn_upstream="$(
			git log --first-parent -1 \
				--grep="^git-svn-id: \(${svn_url_pattern#??}\)" 2>/dev/null
		)"

		if [ -n "$svn_upstream" ]; then
			# extract the URI, assuming --grep matched the last line
			svn_upstream=${svn_upstream##*$LF}  # last line
			svn_upstream=${svn_upstream#*: }    # UPSTRM@N HASH
			svn_upstream=${svn_upstream%@*}     # UPSTRM

			case ${LF}${svn_remotes} in
			*"${LF}${svn_upstream}${LF}"*)
				# grep indeed matched the last line - it's our remote
				# default branch name for checkouts with no layout:
				upstream_type=${GIT_SVN_ID:-git-svn}
				;;
			*)
				# the commit message includes one of our remotes, but
				# it's not at the last line. is $svn_upstream junk?
				upstream_type=${svn_upstream#/}
				;;
			esac
		elif [ "svn+git" = "$upstream_type" ]; then
			upstream_type="@{upstream}"
		fi
		;;
	esac

	# Find how many commits we are ahead/behind our upstream
	if [ -z "$legacy" ]; then
		count="$(git rev-list --count --left-right \
				"$upstream_type"...HEAD 2>/dev/null)"
	else
		# produce equivalent output to --count for older versions of git
		local commits
		if commits="$(git rev-list --left-right "$upstream_type"...HEAD 2>/dev/null)"
		then
			local commit behind=0 ahead=0
			for commit in $commits
			do
				case "$commit" in
				"<"*) behind=$((behind+1)) ;;
				*)    ahead=$((ahead+1))   ;;
				esac
			done
			count="$behind	$ahead"
		else
			count=""
		fi
	fi

	# calculate the result
	if [ -z "$verbose" ]; then
		case "$count" in
		"") # no upstream
			p="" ;;
		"0	0") # equal to upstream
			p="=" ;;
		"0	"*) # ahead of upstream
			p=">" ;;
		*"	0") # behind upstream
			p="<" ;;
		*)	    # diverged from upstream
			p="<>" ;;
		esac
	else # verbose, set upstream instead of p
		case "$count" in
		"") # no upstream
			upstream="" ;;
		"0	0") # equal to upstream
			upstream="|u=" ;;
		"0	"*) # ahead of upstream
			upstream="|u+${count#0	}" ;;
		*"	0") # behind upstream
			upstream="|u-${count%	0}" ;;
		*)	    # diverged from upstream
			upstream="|u+${count#*	}-${count%	*}" ;;
		esac
		if [ -n "$count" ] && [ -n "$name" ]; then
			__git_ps1_upstream_name=$(git rev-parse \
				--abbrev-ref "$upstream_type" 2>/dev/null)
			if [ "$pcmode" = yes ] && [ "$ps1_expanded" = yes ]; then
				upstream="$upstream \${__git_ps1_upstream_name}"
			else
				upstream="$upstream ${__git_ps1_upstream_name}"
				# not needed anymore; keep user's
				# environment clean
				unset __git_ps1_upstream_name
			fi
		fi
	fi

}

# Helper function that is meant to be called from __git_ps1.  It
# injects color codes into the appropriate gitstring variables used
# to build a gitstring. Colored variables are responsible for clearing
# their own color.
__git_ps1_colorize_gitstring ()
{
	if [ -n "${ZSH_VERSION-}" ]; then
		local c_red='%F{red}'
		local c_green='%F{green}'
		local c_lblue='%F{blue}'
		local c_clear='%f'
	else
		# \001 (SOH) and \002 (STX) are 0-width substring markers
		# which bash/readline identify while calculating the prompt
		# on-screen width - to exclude 0-screen-width esc sequences.
		local c_pre="${GIT_PS1_COLOR_PRE-$__git_SOH}${__git_ESC}["
		local c_post="m${GIT_PS1_COLOR_POST-$__git_STX}"

		local c_red="${c_pre}31${c_post}"
		local c_green="${c_pre}32${c_post}"
		local c_lblue="${c_pre}1;34${c_post}"
		local c_clear="${c_pre}0${c_post}"
	fi
	local bad_color="$c_red"
	local ok_color="$c_green"
	local flags_color="$c_lblue"

	local branch_color=""
	if [ "$detached" = no ]; then
		branch_color="$ok_color"
	else
		branch_color="$bad_color"
	fi
	if [ -n "$c" ]; then
		c="$branch_color$c$c_clear"
	fi
	b="$branch_color$b$c_clear"

	if [ -n "$w" ]; then
		w="$bad_color$w$c_clear"
	fi
	if [ -n "$i" ]; then
		i="$ok_color$i$c_clear"
	fi
	if [ -n "$s" ]; then
		s="$flags_color$s$c_clear"
	fi
	if [ -n "$u" ]; then
		u="$bad_color$u$c_clear"
	fi
}

# Helper function to read the first line of a file into a variable.
# __git_eread requires 2 arguments, the file path and the name of the
# variable, in that order.
__git_eread ()
{
	test -r "$1" && IFS=$__git_CRLF read -r "$2" <"$1"
}

# see if a cherry-pick or revert is in progress, if the user has committed a
# conflict resolution with 'git commit' in the middle of a sequence of picks or
# reverts then CHERRY_PICK_HEAD/REVERT_HEAD will not exist so we have to read
# the todo file.
__git_sequencer_status ()
{
	local todo
	if test -f "$g/CHERRY_PICK_HEAD"
	then
		r="|CHERRY-PICKING"
		return 0;
	elif test -f "$g/REVERT_HEAD"
	then
		r="|REVERTING"
		return 0;
	elif __git_eread "$g/sequencer/todo" todo
	then
		case "$todo" in
		p[\ \	]|pick[\ \	]*)
			r="|CHERRY-PICKING"
			return 0
		;;
		revert[\ \	]*)
			r="|REVERTING"
			return 0
		;;
		esac
	fi
	return 1
}

# __git_ps1 accepts 0 or 1 arguments (i.e., format string)
# when called from PS1 using command substitution
# in this mode it prints text to add to bash PS1 prompt (includes branch name)
#
# __git_ps1 requires 2 or 3 arguments when called from PROMPT_COMMAND (pc)
# in that case it _sets_ PS1. The arguments are parts of a PS1 string.
# when two arguments are given, the first is prepended and the second appended
# to the state string when assigned to PS1.
# The optional third parameter will be used as printf format string to further
# customize the output of the git-status string.
# In this mode you can request colored hints using GIT_PS1_SHOWCOLORHINTS=true
__git_ps1 ()
{
	# preserve exit status
	local exit="$?"
	local pcmode=no
	local detached=no
	local ps1pc_start='\u@\h:\w '
	local ps1pc_end='\$ '
	local printf_format=' (%s)'

	case "$#" in
		2|3)	pcmode=yes
			ps1pc_start="$1"
			ps1pc_end="$2"
			printf_format="${3:-$printf_format}"
			# set PS1 to a plain prompt so that we can
			# simply return early if the prompt should not
			# be decorated
			PS1="$ps1pc_start$ps1pc_end"
		;;
		0|1)	printf_format="${1:-$printf_format}"
		;;
		*)	return "$exit"
		;;
	esac

	# ps1_expanded:  This variable is set to 'yes' if the shell
	# subjects the value of PS1 to parameter expansion:
	#
	#   * bash does unless the promptvars option is disabled
	#   * zsh does not unless the PROMPT_SUBST option is set
	#   * POSIX shells always do
	#
	# If the shell would expand the contents of PS1 when drawing
	# the prompt, a raw ref name must not be included in PS1.
	# This protects the user from arbitrary code execution via
	# specially crafted ref names.  For example, a ref named
	# 'refs/heads/$(IFS=_;cmd=sudo_rm_-rf_/;$cmd)' might cause the
	# shell to execute 'sudo rm -rf /' when the prompt is drawn.
	#
	# Instead, the ref name should be placed in a separate global
	# variable (in the __git_ps1_* namespace to avoid colliding
	# with the user's environment) and that variable should be
	# referenced from PS1.  For example:
	#
	#     __git_ps1_foo=$(do_something_to_get_ref_name)
	#     PS1="...stuff...\${__git_ps1_foo}...stuff..."
	#
	# If the shell does not expand the contents of PS1, the raw
	# ref name must be included in PS1.
	#
	# The value of this variable is only relevant when in pcmode.
	#
	# Assume that the shell follows the POSIX specification and
	# expands PS1 unless determined otherwise.  (This is more
	# likely to be correct if the user has a non-bash, non-zsh
	# shell and safer than the alternative if the assumption is
	# incorrect.)
	#
	local ps1_expanded=yes
	[ -z "${ZSH_VERSION-}" ] || eval '[[ -o PROMPT_SUBST ]]' || ps1_expanded=no
	[ -z "${BASH_VERSION-}" ] || shopt -q promptvars || ps1_expanded=no

	local repo_info rev_parse_exit_code
	repo_info="$(git rev-parse --git-dir --is-inside-git-dir \
		--is-bare-repository --is-inside-work-tree --show-ref-format \
		--short HEAD 2>/dev/null)"
	rev_parse_exit_code="$?"

	if [ -z "$repo_info" ]; then
		return "$exit"
	fi

	local LF="$__git_LF"
	local short_sha=""
	if [ "$rev_parse_exit_code" = "0" ]; then
		short_sha="${repo_info##*$LF}"
		repo_info="${repo_info%$LF*}"
	fi
	local ref_format="${repo_info##*$LF}"
	repo_info="${repo_info%$LF*}"
	local inside_worktree="${repo_info##*$LF}"
	repo_info="${repo_info%$LF*}"
	local bare_repo="${repo_info##*$LF}"
	repo_info="${repo_info%$LF*}"
	local inside_gitdir="${repo_info##*$LF}"
	local g="${repo_info%$LF*}"

	if [ "true" = "$inside_worktree" ] &&
	   [ -n "${GIT_PS1_HIDE_IF_PWD_IGNORED-}" ] &&
	   [ "$(git config --bool bash.hideIfPwdIgnored)" != "false" ] &&
	   git check-ignore -q .
	then
		return "$exit"
	fi

	local sparse=""
	if [ -z "${GIT_PS1_COMPRESSSPARSESTATE-}" ] &&
	   [ -z "${GIT_PS1_OMITSPARSESTATE-}" ] &&
	   [ "$(git config --bool core.sparseCheckout)" = "true" ]; then
		sparse="|SPARSE"
	fi

	local r=""
	local b=""
	local step=""
	local total=""
	if [ -d "$g/rebase-merge" ]; then
		__git_eread "$g/rebase-merge/head-name" b
		__git_eread "$g/rebase-merge/msgnum" step
		__git_eread "$g/rebase-merge/end" total
		r="|REBASE"
	else
		if [ -d "$g/rebase-apply" ]; then
			__git_eread "$g/rebase-apply/next" step
			__git_eread "$g/rebase-apply/last" total
			if [ -f "$g/rebase-apply/rebasing" ]; then
				__git_eread "$g/rebase-apply/head-name" b
				r="|REBASE"
			elif [ -f "$g/rebase-apply/applying" ]; then
				r="|AM"
			else
				r="|AM/REBASE"
			fi
		elif [ -f "$g/MERGE_HEAD" ]; then
			r="|MERGING"
		elif __git_sequencer_status; then
			:
		elif [ -f "$g/BISECT_LOG" ]; then
			r="|BISECTING"
		fi

		if [ -n "$b" ]; then
			:
		elif [ -h "$g/HEAD" ]; then
			# symlink symbolic ref
			b="$(git symbolic-ref HEAD 2>/dev/null)"
		else
			local head=""

			case "$ref_format" in
			files)
				if ! __git_eread "$g/HEAD" head; then
					return "$exit"
				fi

				case $head in
				"ref: "*)
					head="${head#ref: }"
					;;
				*)
					head=""
				esac
				;;
			*)
				head="$(git symbolic-ref HEAD 2>/dev/null)"
				;;
			esac

			if test -z "$head"; then
				detached=yes
				b="$(
				case "${GIT_PS1_DESCRIBE_STYLE-}" in
				(contains)
					git describe --contains HEAD ;;
				(branch)
					git describe --contains --all HEAD ;;
				(tag)
					git describe --tags HEAD ;;
				(describe)
					git describe HEAD ;;
				(* | default)
					git describe --tags --exact-match HEAD ;;
				esac 2>/dev/null)" ||

				b="$short_sha..."
				b="($b)"
			else
				b="$head"
			fi
		fi
	fi

	if [ -n "$step" ] && [ -n "$total" ]; then
		r="$r $step/$total"
	fi

	local conflict="" # state indicator for unresolved conflicts
	if [ "${GIT_PS1_SHOWCONFLICTSTATE-}" = "yes" ] &&
	   [ "$(git ls-files --unmerged 2>/dev/null)" ]; then
		conflict="|CONFLICT"
	fi

	local w=""
	local i=""
	local s=""
	local u=""
	local h=""
	local c=""
	local p="" # short version of upstream state indicator
	local upstream="" # verbose version of upstream state indicator

	if [ "true" = "$inside_gitdir" ]; then
		if [ "true" = "$bare_repo" ]; then
			c="BARE:"
		else
			b="GIT_DIR!"
		fi
	elif [ "true" = "$inside_worktree" ]; then
		if [ -n "${GIT_PS1_SHOWDIRTYSTATE-}" ] &&
		   [ "$(git config --bool bash.showDirtyState)" != "false" ]
		then
			git diff --no-ext-diff --quiet || w="*"
			git diff --no-ext-diff --cached --quiet || i="+"
			if [ -z "$short_sha" ] && [ -z "$i" ]; then
				i="#"
			fi
		fi
		if [ -n "${GIT_PS1_SHOWSTASHSTATE-}" ] &&
		   git rev-parse --verify --quiet refs/stash >/dev/null
		then
			s="$"
		fi

		if [ -n "${GIT_PS1_SHOWUNTRACKEDFILES-}" ] &&
		   [ "$(git config --bool bash.showUntrackedFiles)" != "false" ] &&
		   git ls-files --others --exclude-standard --directory --no-empty-directory --error-unmatch -- ':/*' >/dev/null 2>/dev/null
		then
			u="%${ZSH_VERSION+%}"
		fi

		if [ -n "${GIT_PS1_COMPRESSSPARSESTATE-}" ] &&
		   [ "$(git config --bool core.sparseCheckout)" = "true" ]; then
			h="?"
		fi

		if [ -n "${GIT_PS1_SHOWUPSTREAM-}" ]; then
			__git_ps1_show_upstream
		fi
	fi

	local z="${GIT_PS1_STATESEPARATOR- }"

	b=${b##refs/heads/}
	if [ "$pcmode" = yes ] && [ "$ps1_expanded" = yes ]; then
		__git_ps1_branch_name=$b
		b="\${__git_ps1_branch_name}"
	fi

	if [ -n "${GIT_PS1_SHOWCOLORHINTS-}" ]; then
		__git_ps1_colorize_gitstring
	fi

	local f="$h$w$i$s$u$p"
	local gitstring="$c$b${f:+$z$f}${sparse}$r${upstream}${conflict}"

	if [ "$pcmode" = yes ]; then
		if [ "${__git_printf_supports_v-}" != yes ]; then
			gitstring=$(printf -- "$printf_format" "$gitstring")
		else
			printf -v gitstring -- "$printf_format" "$gitstring"
		fi
		PS1="$ps1pc_start$gitstring$ps1pc_end"
	else
		printf -- "$printf_format" "$gitstring"
	fi

	return "$exit"
}



readonly DO_NOT_TRACK=1
# do_not_track.env
# A comprehensive collection of environment variables that opt out of telemetry,
# analytics, and data collection in CLI tools, frameworks, and SDKs.
#
# Usage:
#   Shell (bash/zsh):   set -a && source do_not_track.env && set +a
#   direnv:             copy contents into .envrc
#   Docker Compose:     env_file: do_not_track.env
#   CI/CD:              export vars in your pipeline environment
#
# Source: https://github.com/alloydwhitlock/do-not-track-cli
# Contributing: see README.md

# ──────────────────────────────────────────────
# Universal / Cross-tool Standard
# ──────────────────────────────────────────────
# Many modern tools check DO_NOT_TRACK=1 before sending telemetry.
# Setting this is a good baseline even for tools not listed below.
# See: https://donottrack.sh

# ──────────────────────────────────────────────
# JavaScript / TypeScript Frameworks
# ──────────────────────────────────────────────

# Angular CLI
readonly NG_CLI_ANALYTICS=false
readonly NG_CLI_ANALYTICS_SHARE=false

# Astro
readonly ASTRO_TELEMETRY_DISABLED=1

# Gatsby
readonly GATSBY_TELEMETRY_DISABLED=1

# Next.js
readonly NEXT_TELEMETRY_DISABLED=1

# Nuxt.js
readonly NUXT_TELEMETRY_DISABLED=1

# Strapi
readonly STRAPI_TELEMETRY_DISABLED=true
readonly STRAPI_DISABLE_UPDATE_NOTIFICATION=true

# Turborepo
readonly TURBO_TELEMETRY_DISABLED=1

# VueDX
readonly VUEDX_TELEMETRY=off

# webhint
readonly HINT_TELEMETRY=off

# Webiny
readonly REACT_APP_WEBINY_TELEMETRY=false

# SKU (Seek's build toolchain)
readonly SKU_TELEMETRY=false

# Cube.js
readonly CUBEJS_TELEMETRY=false

# ──────────────────────────────────────────────
# Package Managers & Dependency Tools
# ──────────────────────────────────────────────

# Homebrew (macOS/Linux)
readonly HOMEBREW_NO_ANALYTICS=1
readonly HOMEBREW_NO_ANALYTICS_THIS_RUN=1

# Yarn 2+
readonly YARN_ENABLE_TELEMETRY=0

# ──────────────────────────────────────────────
# Language Runtimes & Build Tools
# ──────────────────────────────────────────────

# .NET Core SDK
readonly DOTNET_CLI_TELEMETRY_OPTOUT=1

# .NET Interactive
readonly DOTNET_INTERACTIVE_CLI_TELEMETRY_OPTOUT=1

# dotnet-svcutil
readonly DOTNET_SVCUTIL_TELEMETRY_OPTOUT=1

# Go (golang.org/x/telemetry, added in Go 1.23)
readonly GOTELEMETRY=off

# ML.NET CLI
readonly MLDOTNET_CLI_TELEMETRY_OPTOUT=1

# mssql-cli
readonly MSSQL_CLI_TELEMETRY_OPTOUT=1

# PowerShell Core
readonly POWERSHELL_TELEMETRY_OPTOUT=1

# Bun (also respects DO_NOT_TRACK=1 above)
# BUN_DISABLE_TELEMETRY=1  # future; currently DO_NOT_TRACK=1 is sufficient

# choosenim (Nim version manager)
readonly CHOOSENIM_NO_ANALYTICS=1

# Nuke (build system for .NET)
readonly NUKE_TELEMETRY_OPTOUT=1

# ──────────────────────────────────────────────
# Infrastructure as Code
# ──────────────────────────────────────────────

# Terraform / OpenTofu / Packer / Vault / Consul / Weave Net / WKSctl / CDK for Terraform
# CHECKPOINT_DISABLE is a HashiCorp-wide convention used by multiple tools.
readonly CHECKPOINT_DISABLE=1

# Terraform Provider for Azure
readonly ARM_DISABLE_TERRAFORM_PARTNER_ID=true

# F5 BIG-IP Terraform provider
readonly TEEM_DISABLE=true

# Pulumi
readonly PULUMI_SKIP_UPDATE_CHECK=true

# Earthly
readonly EARTHLY_DISABLE_ANALYTICS=1

# Batect
readonly BATECT_ENABLE_TELEMETRY=false

# Pants (Python build system)
readonly PANTS_ANONYMOUS_TELEMETRY_ENABLED=false

# werf
readonly WERF_TELEMETRY=0

# AWS CDK
readonly CDK_DISABLE_CLI_TELEMETRY=true

# ──────────────────────────────────────────────
# Cloud Provider CLIs
# ──────────────────────────────────────────────

# Google Cloud SDK (gcloud)
readonly CLOUDSDK_CORE_DISABLE_USAGE_REPORTING=true

# Azure CLI
readonly AZURE_CORE_COLLECT_TELEMETRY=0

# AWS SAM CLI
readonly SAM_CLI_TELEMETRY=0

# Salesforce CLI (sf / sfdx)
readonly SF_DISABLE_TELEMETRY=true
readonly SFDX_DISABLE_TELEMETRY=true

# GitHub CLI (gh) — added in v2.91.0, April 2026
readonly GH_TELEMETRY=false

# Supabase CLI (also respects DO_NOT_TRACK=1 above)
readonly SUPABASE_TELEMETRY_DISABLED=1

# Vercel CLI
readonly VERCEL_TELEMETRY_DISABLED=1

# Railway (also respects DO_NOT_TRACK=1 above)
readonly RAILWAY_NO_TELEMETRY=1

# Cloudflare Wrangler
readonly WRANGLER_SEND_METRICS=false

# ──────────────────────────────────────────────
# Databases & Data Platforms
# ──────────────────────────────────────────────

# InfluxDB
readonly INFLUXD_REPORTING_DISABLED=true

# MeiliSearch
readonly MEILI_NO_ANALYTICS=true

# NocoDB
readonly NC_DISABLE_TELE=1

# Hasura GraphQL Engine
readonly HASURA_GRAPHQL_ENABLE_TELEMETRY=false
 
# Meltano
readonly MELTANO_DISABLE_TRACKING=true

# Prisma (uses CHECKPOINT_DISABLE — already set above)

# Quickwit
readonly DISABLE_QUICKWIT_TELEMETRY=1

# ──────────────────────────────────────────────
# API Clients & SDKs
# ──────────────────────────────────────────────

# Expo / React Native
readonly EXPO_NO_TELEMETRY=1

# Fastlane
readonly FASTLANE_OPT_OUT_USAGE=YES

# Feast (feature store)
readonly FEAST_TELEMETRY=false

# Mattermost Server
readonly MM_LOGSETTINGS_ENABLEDIAGNOSTICS=false
readonly MM_SERVICESETTINGS_ENABLESECURITYFIXALERT=false

# Canvas LMS
readonly CANVAS_LMS_STATS_COLLECTION=opt_out

# otel-launcher-node (Lightstep host metrics)
readonly LS_METRICS_HOST_ENABLED=0

# One Codex
readonly ONE_CODEX_NO_TELEMETRY=true

# Ory
readonly SQA_OPT_OUT=true

# Oryx (Microsoft build tool)
readonly ORYX_DISABLE_TELEMETRY=true

# PROSE Code Accelerator SDK (Microsoft Research)
readonly PROSE_TELEMETRY_OPTOUT=1

# RASA (conversational AI)
readonly RASA_TELEMETRY_ENABLED=false

# Quilt (data versioning)
readonly QUILT_DISABLE_USAGE_METRICS=true

# ReportPortal
readonly REPORTPORTAL_CLIENT_JS_NO_ANALYTICS=true
readonly AGENT_NO_ANALYTICS=1

# RESTler (REST API fuzzer)
readonly RESTLER_TELEMETRY_OPTOUT=1

# Rockset CLI
readonly ROCKSET_CLI_TELEMETRY_OPTOUT=1

# Rover CLI (Apollo GraphQL)
readonly APOLLO_TELEMETRY_DISABLED=1

# Salto CLI
readonly SALTO_TELEMETRY_DISABLE=1

# Redocly CLI
readonly REDOCLY_TELEMETRY=off

# Encore
readonly DISABLE_ENCORE_TELEMETRY=1

# Stripe CLI
readonly STRIPE_CLI_TELEMETRY_OPTOUT=1

# ──────────────────────────────────────────────
# Serverless & FaaS
# ──────────────────────────────────────────────

# Serverless Framework
readonly SLS_TELEMETRY_DISABLED=1
readonly SLS_TRACKING_DISABLED=1

# ──────────────────────────────────────────────
# DevOps & Platform Tools
# ──────────────────────────────────────────────

# App Center CLI
readonly MOBILE_CENTER_TELEMETRY=off

# Arduino CLI
readonly ARDUINO_METRICS_ENABLED=false

# Appc Daemon (Titanium)
readonly APPCD_TELEMETRY=0

# Bot Framework CLI
readonly BF_CLI_TELEMETRY=false

# Chef Workstation
readonly CHEF_TELEMETRY_OPT_OUT=1

# CocoaPods
readonly COCOAPODS_DISABLE_STATS=true

# Dagster
readonly DAGSTER_DISABLE_TELEMETRY=1

# decK (Kong declarative config)
readonly DECK_ANALYTICS=off

# Eternal Terminal
readonly ET_NO_TELEMETRY=1

# F5 CLI
readonly F5_ALLOW_TELEMETRY=false

# Gemini CLI
readonly GEMINI_TELEMETRY_ENABLED=false

# Hugging Face Hub (python transformers / diffusers / datasets)
readonly HF_HUB_DISABLE_TELEMETRY=1

# Hookdeck CLI
readonly HOOKDECK_CLI_TELEMETRY_OPTOUT=1

# Humbug (Python library used by several tools)
readonly BUGGER_OFF=1

# Infracost
readonly INFRACOST_SELF_HOSTED_TELEMETRY=false

# KICS (security scanner)
readonly KICS_COLLECT_TELEMETRY=0
readonly DISABLE_CRASH_REPORT=1

# kPow (Kafka UI)
readonly ALLOW_UI_ANALYTICS=false

# LYNX VFX
readonly LYNX_ANALYTICS=0

# MSLab
readonly MSLAB_TELEMETRY_LEVEL=None

# Netdata (also respects DO_NOT_TRACK=1 above)
# DO_NOT_TRACK is already set above

# PnP PowerShell
readonly PNPPOWERSHELL_DISABLETELEMETRY=true

# Telepresence (CNCF)
readonly SCOUT_DISABLE=1

# Tilt (k8s dev tool; also respects DO_NOT_TRACK=1)
# DO_NOT_TRACK is already set above

# Tuist
readonly TUIST_STATS_OPT_OUT=1

# Vagrant
readonly VAGRANT_CHECKPOINT_DISABLE=1
readonly VAGRANT_BOX_UPDATE_CHECK_DISABLE=1

# vstest
readonly VSTEST_TELEMETRY_OPTEDIN=0

# AutomatedLab
readonly AUTOMATEDLAB_TELEMETRY_OPTIN=0
readonly AUTOMATEDLAB_TELEMETRY_OPTOUT=1

# Dagger (also respects DO_NOT_TRACK=1)
# DO_NOT_TRACK is already set above

# aliBuild (ALICE/CERN)
readonly ALIBUILD_NO_ANALYTICS=1

# kubeapt (Kubernetes dashboard)
readonly DASH_DISABLE_TELEMETRY=1

# Testim Root Cause (failure analysis)
readonly SUGGESTIONS_OPT_OUT=1

# Carbon Design System
readonly CARBON_TELEMETRY_DISABLED=1

# Automagica
readonly AUTOMAGICA_NO_TELEMETRY=1

# JavaScript debugger (VSCode)
readonly DA_TEST_DISABLE_TELEMETRY=1

# Azure Application Insights VSCode extension
readonly AITOOLSVSCODE_DISABLETELEMETRY=1

# ──────────────────────────────────────────────
# Aggressive / Opt-in
# ──────────────────────────────────────────────
# These variables go beyond disabling telemetry. They block network access,
# suppress system notifications, or use generic names likely to collide with
# other tools in your environment. They are commented out by default.
#
# Uncomment only the ones you want, and verify they don't break other tools.

# Hugging Face Hub — blocks ALL outbound connections to hf.co.
# This prevents model and dataset downloads, not just usage reporting.
# Only set this in fully offline or air-gapped environments.
readonly HF_HUB_OFFLINE=1

# AccessMap — disables analytics for the AccessMap routing tool, but the
# variable name ANALYTICS is generic enough to interfere with other tools
# that check $ANALYTICS in their own startup logic.
readonly ANALYTICS=no

# projector-cli — disables telemetry for JetBrains projector-cli, but
# TELEMETRY_ENABLED is a common pattern used by many tools. Setting this
# globally may silently affect other tools in your environment.
readonly TELEMETRY_ENABLED=0
readonly EDITOR=/usr/bin/vim
readonly GIT_SSH_COMMAND="ssh -C -I /usr/lib64/opensc-pkcs11.so"
readonly LD_PRELOAD
readonly LD_LIBRARY_PATH
alias htop="htop --drop-capabilities=strict"
alias ls="ls --color=auto -lhaZ"
alias ps="ps -Z"
clear;fastfetch -l Aperture  --pipe false
readonly PROMPT_COMMAND='PS1_CMD1=$(id -Z); PS1_CMD2=$(id -u); PS1_CMD3=$(ip route get 1.1.1.1 | awk -F"src " '"'"'NR == 1{ split($2, a," ");print a[1]}'"'"'); PS1_CMD4=$(pwd); PS1_CMD5=$(__git_ps1 " (%s)")'; PS1='\[\e[91m\][\[\e[93m\]${PS1_CMD1}\[\e[91m\]]\[\e[35m\]\u\[\e[0m\]:\[\e[95m\]${PS1_CMD2}\[\e[0m\]@\[\e[96m\]\h\[\e[0m\]:\[\e[96m\]${PS1_CMD3}\[\e[0m\](\[\e[92m\]${PS1_CMD4}\[\e[32m\]${PS1_CMD5}\[\e[0m\])\n\[\e[94m\]#\[\e[93m\]\T\[\e[91m\]>\[\e[0m\] '
readonly PS1=$PS1
